# fly.toml app configuration file generated for mnist-ai-data-recognizer on 2024-11-13T13:16:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mnist-ai-data-recognizer'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
